### ISSUE TITLE
Interview question

### ISSUE THREAD

**Issue by KalyanKumar-4** [TheSYNcoder/InterviewPrep#25]
I faced this interview question.It is very easy but I'm willing to share with you
Prob: Suppose if there is small plant in a pond.The size of plant is doubling on everyday in length wise.If it takes 30 days to cover surface area of pond than in how many days it'll cover the half of surface area of pond?

**Comment by CubixPro** [comment]
Can you mention the company? It would be favourable if you provide a link to the question or the solution.
