### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by bisakhmondal** [TheSYNcoder/InterviewPrep#3]
Currently, a few solutions link uses the absolute GitHub URL in readme markdown. It would be great to have a relative path attached to each solution instead of a direct URL.
for e.g.
`[Solution](Solutions/triangle.cpp)
`
instead of 
`[Solution](https://github.com/TheSYNcoder/InterviewPrep/blob/master/Solutions/FloydLoopDetection.cpp)`

Thanks.

**Comment by TheSYNcoder** [comment]
Yaa can be done !

**Comment by CubixPro** [comment]
Ok this has been done.

**Comment by bisakhmondal** [comment]
Thanks @CubixPro :+1:
